"""Initial migration

Revision ID: 392b24e2b4e4
Revises:
Create Date: 2026-03-21 19:04:46.107061

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "392b24e2b4e4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("hashed_password", sa.Text(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("APPLICANT", "EMPLOYER", "CURATOR", name="userrole", native_enum=False),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_table(
        "profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.Text(), nullable=False),
        sa.Column("last_name", sa.Text(), nullable=False),
        sa.Column("middle_name", sa.Text(), nullable=True),
        sa.Column("university", sa.Text(), nullable=True),
        sa.Column("graduation_year", sa.Integer(), nullable=True),
        sa.Column(
            "skills", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column(
            "social_links",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "privacy_settings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='{"public_profile": true, "show_contacts": false, "show_github": true}',
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_profiles_created_at"), "profiles", ["created_at"], unique=False)
    op.create_index(op.f("ix_profiles_first_name"), "profiles", ["first_name"], unique=False)
    op.create_index(op.f("ix_profiles_last_name"), "profiles", ["last_name"], unique=False)
    op.create_index(
        "ix_profiles_privacy_gin",
        "profiles",
        ["privacy_settings"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_profiles_skills_gin", "profiles", ["skills"], unique=False, postgresql_using="gin"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_profiles_skills_gin", table_name="profiles", postgresql_using="gin")
    op.drop_index("ix_profiles_privacy_gin", table_name="profiles", postgresql_using="gin")
    op.drop_index(op.f("ix_profiles_last_name"), table_name="profiles")
    op.drop_index(op.f("ix_profiles_first_name"), table_name="profiles")
    op.drop_index(op.f("ix_profiles_created_at"), table_name="profiles")
    op.drop_table("profiles")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
