"""new tables

Revision ID: 41aa86a76f51
Revises: 392b24e2b4e4
Create Date: 2026-03-23 13:49:34.687378

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "41aa86a76f51"
down_revision: str | Sequence[str] | None = "392b24e2b4e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("legal_name", sa.Text(), nullable=True),
        sa.Column("inn", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("short_description", sa.Text(), nullable=True),
        sa.Column("industry", sa.Text(), nullable=True),
        sa.Column("company_size", sa.Text(), nullable=True),
        sa.Column("founded_year", sa.Integer(), nullable=True),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column("country", sa.Text(), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column("logo_url", sa.Text(), nullable=True),
        sa.Column("cover_url", sa.Text(), nullable=True),
        sa.Column(
            "media", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("website_url", sa.Text(), nullable=True),
        sa.Column("corporate_email", sa.Text(), nullable=True),
        sa.Column(
            "social_links",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "verification_status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "REVOKED",
                name="verificationstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("verified_at", sa.Uuid(), nullable=True),
        sa.Column("verified_by_id", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["verified_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id"),
    )
    op.create_index(op.f("ix_companies_city"), "companies", ["city"], unique=False)
    op.create_index("ix_companies_city_active", "companies", ["city", "is_active"], unique=False)
    op.create_index(op.f("ix_companies_created_at"), "companies", ["created_at"], unique=False)
    op.create_index(op.f("ix_companies_industry"), "companies", ["industry"], unique=False)
    op.create_index(op.f("ix_companies_inn"), "companies", ["inn"], unique=True)
    op.create_index(op.f("ix_companies_is_active"), "companies", ["is_active"], unique=False)
    op.create_index(
        "ix_companies_location", "companies", ["location"], unique=False, postgresql_using="gist"
    )
    op.create_index(op.f("ix_companies_name"), "companies", ["name"], unique=False)
    op.create_index(
        "ix_companies_verification", "companies", ["verification_status", "is_active"], unique=False
    )
    op.create_index(
        op.f("ix_companies_verification_status"), "companies", ["verification_status"], unique=False
    )
    op.create_table(
        "contacts",
        sa.Column("requester_id", sa.UUID(), nullable=False),
        sa.Column("addressee_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ACCEPTED",
                "REJECTED",
                "BLOCKED",
                name="contactstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["addressee_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["requester_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("requester_id", "addressee_id", name="uq_contact_pair"),
    )
    op.create_index(op.f("ix_contacts_addressee_id"), "contacts", ["addressee_id"], unique=False)
    op.create_index(
        "ix_contacts_addressee_status", "contacts", ["addressee_id", "status"], unique=False
    )
    op.create_index(op.f("ix_contacts_created_at"), "contacts", ["created_at"], unique=False)
    op.create_index(op.f("ix_contacts_requester_id"), "contacts", ["requester_id"], unique=False)
    op.create_index(op.f("ix_contacts_status"), "contacts", ["status"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("recipient_id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "APPLICATION_STATUS",
                "NEW_APPLICATION",
                "CONTACT_REQUEST",
                "CONTACT_ACCEPTED",
                "NEW_MESSAGE",
                "OPPORTUNITY_EXPIRED",
                "COMPANY_VERIFIED",
                "RECOMMENDATION",
                "SYSTEM",
                name="notificationtype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["recipient_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_created_at"), "notifications", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_notifications_is_read"), "notifications", ["is_read"], unique=False)
    op.create_index(
        op.f("ix_notifications_recipient_id"), "notifications", ["recipient_id"], unique=False
    )
    op.create_index(
        "ix_notifications_recipient_unread",
        "notifications",
        ["recipient_id", "is_read"],
        unique=False,
    )
    op.create_index(op.f("ix_notifications_type"), "notifications", ["type"], unique=False)
    op.create_table(
        "reviews",
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column(
            "target_type",
            sa.Enum("COMPANY", "OPPORTUNITY", name="reviewtarget", native_enum=False),
            nullable=False,
        ),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("rating_culture", sa.Integer(), nullable=True),
        sa.Column("rating_career", sa.Integer(), nullable=True),
        sa.Column("rating_salary", sa.Integer(), nullable=True),
        sa.Column("rating_management", sa.Integer(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("pros", sa.Text(), nullable=True),
        sa.Column("cons", sa.Text(), nullable=True),
        sa.Column("employment_period", sa.Text(), nullable=True),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("is_anonymous", sa.Boolean(), nullable=False),
        sa.Column("moderated_by_id", sa.UUID(), nullable=True),
        sa.Column("moderation_comment", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["moderated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reviews_author_id"), "reviews", ["author_id"], unique=False)
    op.create_index(
        "ix_reviews_author_target",
        "reviews",
        ["author_id", "target_type", "target_id"],
        unique=True,
    )
    op.create_index(op.f("ix_reviews_created_at"), "reviews", ["created_at"], unique=False)
    op.create_index(op.f("ix_reviews_is_published"), "reviews", ["is_published"], unique=False)
    op.create_index(
        "ix_reviews_target", "reviews", ["target_type", "target_id", "is_published"], unique=False
    )
    op.create_index(op.f("ix_reviews_target_id"), "reviews", ["target_id"], unique=False)
    op.create_index(op.f("ix_reviews_target_type"), "reviews", ["target_type"], unique=False)
    op.create_table(
        "skills",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "LANGUAGE",
                "FRAMEWORK",
                "DATABASE",
                "DEVOPS",
                "CLOUD",
                "MOBILE",
                "AI_ML",
                "DESIGN",
                "MANAGEMENT",
                "SOFT",
                "OTHER",
                name="skillcategory",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon_url", sa.Text(), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("is_approved", sa.Boolean(), nullable=False),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_skills_category"), "skills", ["category"], unique=False)
    op.create_index(
        "ix_skills_category_approved", "skills", ["category", "is_approved"], unique=False
    )
    op.create_index(op.f("ix_skills_created_at"), "skills", ["created_at"], unique=False)
    op.create_index(op.f("ix_skills_is_approved"), "skills", ["is_approved"], unique=False)
    op.create_index(op.f("ix_skills_name"), "skills", ["name"], unique=True)
    op.create_index(op.f("ix_skills_slug"), "skills", ["slug"], unique=True)
    op.create_index("ix_skills_usage", "skills", ["usage_count"], unique=False)
    op.create_table(
        "tags",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column("color", sa.Text(), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("is_approved", sa.Boolean(), nullable=False),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tags_category"), "tags", ["category"], unique=False)
    op.create_index(op.f("ix_tags_created_at"), "tags", ["created_at"], unique=False)
    op.create_index(op.f("ix_tags_is_approved"), "tags", ["is_approved"], unique=False)
    op.create_index(op.f("ix_tags_name"), "tags", ["name"], unique=True)
    op.create_index(op.f("ix_tags_slug"), "tags", ["slug"], unique=True)
    op.create_table(
        "company_verifications",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "REVOKED",
                name="verificationstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("inn", sa.Text(), nullable=True),
        sa.Column("inn_verified", sa.Boolean(), nullable=False),
        sa.Column("corporate_email", sa.Text(), nullable=True),
        sa.Column("email_domain_verified", sa.Boolean(), nullable=False),
        sa.Column(
            "verification_links",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "documents",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("curator_comment", sa.Text(), nullable=True),
        sa.Column("reviewed_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reviewed_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_company_verifications_company", "company_verifications", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_company_verifications_created_at"),
        "company_verifications",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_company_verifications_status", "company_verifications", ["status"], unique=False
    )
    op.create_table(
        "favorite_companies",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "company_id", name="uq_fav_company_once"),
    )
    op.create_index(
        op.f("ix_favorite_companies_company_id"), "favorite_companies", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_favorite_companies_created_at"), "favorite_companies", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_favorite_companies_user_id"), "favorite_companies", ["user_id"], unique=False
    )
    op.create_table(
        "opportunities",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("requirements", sa.Text(), nullable=True),
        sa.Column("responsibilities", sa.Text(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "VACANCY",
                "INTERNSHIP",
                "MENTORING",
                "EVENT",
                name="opportunitytype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "ACTIVE",
                "PAUSED",
                "CLOSED",
                "PLANNED",
                name="opportunitystatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "work_format",
            sa.Enum("OFFICE", "HYBRID", "REMOTE", "ONLINE", name="workformat", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "employment_type",
            sa.Enum(
                "FULL_TIME",
                "PART_TIME",
                "PROJECT",
                "VOLUNTEER",
                name="employmenttype",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "experience_level",
            sa.Enum(
                "INTERN",
                "JUNIOR",
                "MIDDLE",
                "SENIOR",
                "LEAD",
                name="experiencelevel",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("salary_min", sa.Integer(), nullable=True),
        sa.Column("salary_max", sa.Integer(), nullable=True),
        sa.Column("salary_currency", sa.Text(), nullable=False),
        sa.Column("salary_gross", sa.Boolean(), nullable=False),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("event_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("event_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scheduled_publish_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "media", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("contact_name", sa.Text(), nullable=True),
        sa.Column("contact_email", sa.Text(), nullable=True),
        sa.Column("contact_phone", sa.Text(), nullable=True),
        sa.Column("contact_url", sa.Text(), nullable=True),
        sa.Column("max_participants", sa.Integer(), nullable=True),
        sa.Column("current_participants", sa.Integer(), nullable=False),
        sa.Column("views_count", sa.Integer(), nullable=False),
        sa.Column("applications_count", sa.Integer(), nullable=False),
        sa.Column("favorites_count", sa.Integer(), nullable=False),
        sa.Column("is_moderated", sa.Boolean(), nullable=False),
        sa.Column("moderated_by_id", sa.UUID(), nullable=True),
        sa.Column("moderation_comment", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["moderated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_opportunities_active",
        "opportunities",
        ["status", "type"],
        unique=False,
        postgresql_where="status = 'active'",
    )
    op.create_index(op.f("ix_opportunities_city"), "opportunities", ["city"], unique=False)
    op.create_index(
        op.f("ix_opportunities_company_id"), "opportunities", ["company_id"], unique=False
    )
    op.create_index(
        "ix_opportunities_company_status", "opportunities", ["company_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_opportunities_created_at"), "opportunities", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_opportunities_employment_type"), "opportunities", ["employment_type"], unique=False
    )
    op.create_index(
        "ix_opportunities_event_start", "opportunities", ["event_start_at"], unique=False
    )
    op.create_index(
        op.f("ix_opportunities_event_start_at"), "opportunities", ["event_start_at"], unique=False
    )
    op.create_index(
        op.f("ix_opportunities_experience_level"),
        "opportunities",
        ["experience_level"],
        unique=False,
    )
    op.create_index("ix_opportunities_expires", "opportunities", ["expires_at"], unique=False)
    op.create_index(
        op.f("ix_opportunities_expires_at"), "opportunities", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_opportunities_is_moderated"), "opportunities", ["is_moderated"], unique=False
    )
    op.create_index(
        "ix_opportunities_location",
        "opportunities",
        ["location"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index("ix_opportunities_published", "opportunities", ["published_at"], unique=False)
    op.create_index(
        op.f("ix_opportunities_published_at"), "opportunities", ["published_at"], unique=False
    )
    op.create_index(
        "ix_opportunities_salary", "opportunities", ["salary_min", "salary_max"], unique=False
    )
    op.create_index(
        op.f("ix_opportunities_salary_min"), "opportunities", ["salary_min"], unique=False
    )
    op.create_index(op.f("ix_opportunities_status"), "opportunities", ["status"], unique=False)
    op.create_index(op.f("ix_opportunities_title"), "opportunities", ["title"], unique=False)
    op.create_index(op.f("ix_opportunities_type"), "opportunities", ["type"], unique=False)
    op.create_index(
        "ix_opportunities_type_status", "opportunities", ["type", "status"], unique=False
    )
    op.create_index(
        op.f("ix_opportunities_work_format"), "opportunities", ["work_format"], unique=False
    )
    op.create_table(
        "profile_skills",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.Column("proficiency_level", sa.Integer(), nullable=False),
        sa.Column("years_experience", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("profile_id", "skill_id"),
    )
    op.create_index(
        op.f("ix_profile_skills_created_at"), "profile_skills", ["created_at"], unique=False
    )
    op.create_index("ix_profile_skills_profile", "profile_skills", ["profile_id"], unique=False)
    op.create_index("ix_profile_skills_skill", "profile_skills", ["skill_id"], unique=False)
    op.create_table(
        "applications",
        sa.Column("opportunity_id", sa.UUID(), nullable=False),
        sa.Column("applicant_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "VIEWED",
                "ACCEPTED",
                "REJECTED",
                "RESERVE",
                "WITHDRAWN",
                name="applicationstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("cover_letter", sa.Text(), nullable=True),
        sa.Column("cv_url_snapshot", sa.Text(), nullable=True),
        sa.Column("employer_comment", sa.Text(), nullable=True),
        sa.Column("employer_note", sa.Text(), nullable=True),
        sa.Column(
            "status_history",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("viewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_shortlisted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["applicant_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["opportunity_id"], ["opportunities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("opportunity_id", "applicant_id", name="uq_application_once"),
    )
    op.create_index(
        op.f("ix_applications_applicant_id"), "applications", ["applicant_id"], unique=False
    )
    op.create_index(
        "ix_applications_applicant_status", "applications", ["applicant_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_applications_created_at"), "applications", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_applications_is_shortlisted"), "applications", ["is_shortlisted"], unique=False
    )
    op.create_index(
        op.f("ix_applications_opportunity_id"), "applications", ["opportunity_id"], unique=False
    )
    op.create_index(
        "ix_applications_opportunity_status",
        "applications",
        ["opportunity_id", "status"],
        unique=False,
    )
    op.create_index("ix_applications_status", "applications", ["status"], unique=False)
    op.create_table(
        "conversations",
        sa.Column("opportunity_id", sa.UUID(), nullable=True),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_message_preview", sa.Text(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["opportunity_id"], ["opportunities.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversations_created_at"), "conversations", ["created_at"], unique=False
    )
    op.create_index(
        "ix_conversations_last_message", "conversations", ["last_message_at"], unique=False
    )
    op.create_index(
        op.f("ix_conversations_last_message_at"), "conversations", ["last_message_at"], unique=False
    )
    op.create_index(
        op.f("ix_conversations_opportunity_id"), "conversations", ["opportunity_id"], unique=False
    )
    op.create_table(
        "event_registrations",
        sa.Column("opportunity_id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("check_in_code", sa.Text(), nullable=True),
        sa.Column("checked_in_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["opportunity_id"], ["opportunities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("opportunity_id", "profile_id", name="uq_event_registration_once"),
    )
    op.create_index(
        "ix_event_reg_opportunity", "event_registrations", ["opportunity_id"], unique=False
    )
    op.create_index(
        op.f("ix_event_registrations_check_in_code"),
        "event_registrations",
        ["check_in_code"],
        unique=True,
    )
    op.create_index(
        op.f("ix_event_registrations_created_at"),
        "event_registrations",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_registrations_opportunity_id"),
        "event_registrations",
        ["opportunity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_registrations_profile_id"),
        "event_registrations",
        ["profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_registrations_status"), "event_registrations", ["status"], unique=False
    )
    op.create_table(
        "favorites",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("opportunity_id", sa.UUID(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["opportunity_id"], ["opportunities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "opportunity_id", name="uq_favorite_once"),
    )
    op.create_index(op.f("ix_favorites_created_at"), "favorites", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_favorites_opportunity_id"), "favorites", ["opportunity_id"], unique=False
    )
    op.create_index("ix_favorites_user", "favorites", ["user_id"], unique=False)
    op.create_index(op.f("ix_favorites_user_id"), "favorites", ["user_id"], unique=False)
    op.create_table(
        "opportunity_skills",
        sa.Column("opportunity_id", sa.UUID(), nullable=False),
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["opportunity_id"], ["opportunities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("opportunity_id", "skill_id"),
    )
    op.create_index(
        "ix_opp_skills_opportunity", "opportunity_skills", ["opportunity_id"], unique=False
    )
    op.create_index("ix_opp_skills_skill", "opportunity_skills", ["skill_id"], unique=False)
    op.create_index(
        op.f("ix_opportunity_skills_created_at"), "opportunity_skills", ["created_at"], unique=False
    )
    op.create_table(
        "opportunity_tags",
        sa.Column("opportunity_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["opportunity_id"], ["opportunities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("opportunity_id", "tag_id"),
    )
    op.create_index("ix_opp_tags_opportunity", "opportunity_tags", ["opportunity_id"], unique=False)
    op.create_index("ix_opp_tags_tag", "opportunity_tags", ["tag_id"], unique=False)
    op.create_index(
        op.f("ix_opportunity_tags_created_at"), "opportunity_tags", ["created_at"], unique=False
    )
    op.create_table(
        "recommendations",
        sa.Column("sender_id", sa.UUID(), nullable=False),
        sa.Column("recipient_id", sa.UUID(), nullable=False),
        sa.Column("opportunity_id", sa.UUID(), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["opportunity_id"], ["opportunities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["recipient_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sender_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recommendations_created_at"), "recommendations", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_recommendations_is_read"), "recommendations", ["is_read"], unique=False
    )
    op.create_index(
        op.f("ix_recommendations_opportunity_id"),
        "recommendations",
        ["opportunity_id"],
        unique=False,
    )
    op.create_index(
        "ix_recommendations_recipient", "recommendations", ["recipient_id", "is_read"], unique=False
    )
    op.create_index(
        op.f("ix_recommendations_recipient_id"), "recommendations", ["recipient_id"], unique=False
    )
    op.create_index(
        op.f("ix_recommendations_sender_id"), "recommendations", ["sender_id"], unique=False
    )
    op.create_table(
        "conversation_participants",
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("unread_count", sa.Integer(), nullable=False),
        sa.Column("is_muted", sa.Boolean(), nullable=False),
        sa.Column("cleared_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("conversation_id", "user_id"),
    )
    op.create_index(
        "ix_conv_participants_unread",
        "conversation_participants",
        ["user_id", "unread_count"],
        unique=False,
    )
    op.create_index(
        "ix_conv_participants_user", "conversation_participants", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_conversation_participants_created_at"),
        "conversation_participants",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "messages",
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("sender_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("SENT", "DELIVERED", "READ", name="messagestatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("message_type", sa.Text(), nullable=False),
        sa.Column("reply_to_id", sa.UUID(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reply_to_id"], ["messages.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["sender_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_messages_conversation_created",
        "messages",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False
    )
    op.create_index(op.f("ix_messages_created_at"), "messages", ["created_at"], unique=False)
    op.create_index(op.f("ix_messages_is_deleted"), "messages", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_messages_message_type"), "messages", ["message_type"], unique=False)
    op.create_index(op.f("ix_messages_sender_id"), "messages", ["sender_id"], unique=False)
    op.create_index(op.f("ix_messages_status"), "messages", ["status"], unique=False)
    op.create_index(
        "ix_messages_unread",
        "messages",
        ["conversation_id", "status"],
        unique=False,
        postgresql_where="status != 'read' AND is_deleted = false",
    )
    op.create_table(
        "message_attachments",
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("attachment_type", sa.Text(), nullable=False),
        sa.Column("file_name", sa.Text(), nullable=True),
        sa.Column("file_url", sa.Text(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("mime_type", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_message_attachments_message_id"),
        "message_attachments",
        ["message_id"],
        unique=False,
    )
    op.add_column("profiles", sa.Column("faculty", sa.Text(), nullable=True))
    op.add_column("profiles", sa.Column("specialization", sa.Text(), nullable=True))
    op.add_column("profiles", sa.Column("study_year", sa.Integer(), nullable=True))
    op.add_column("profiles", sa.Column("headline", sa.Text(), nullable=True))
    op.add_column("profiles", sa.Column("bio", sa.Text(), nullable=True))
    op.add_column("profiles", sa.Column("avatar_url", sa.Text(), nullable=True))
    op.add_column("profiles", sa.Column("phone", sa.Text(), nullable=True))
    op.add_column("profiles", sa.Column("portfolio_url", sa.Text(), nullable=True))
    op.add_column("profiles", sa.Column("cv_url", sa.Text(), nullable=True))
    op.add_column(
        "profiles",
        sa.Column(
            "career_preferences",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_profiles_skills_gin"), table_name="profiles", postgresql_using="gin")
    op.create_index(
        "ix_profiles_career_prefs_gin",
        "profiles",
        ["career_preferences"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index("ix_profiles_graduation_year", "profiles", ["graduation_year"], unique=False)
    op.create_index("ix_profiles_university", "profiles", ["university"], unique=False)
    op.drop_column("profiles", "skills")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles",
        sa.Column(
            "skills",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index("ix_profiles_university", table_name="profiles")
    op.drop_index("ix_profiles_graduation_year", table_name="profiles")
    op.drop_index("ix_profiles_career_prefs_gin", table_name="profiles", postgresql_using="gin")
    op.create_index(
        op.f("ix_profiles_skills_gin"), "profiles", ["skills"], unique=False, postgresql_using="gin"
    )
    op.drop_column("profiles", "career_preferences")
    op.drop_column("profiles", "cv_url")
    op.drop_column("profiles", "portfolio_url")
    op.drop_column("profiles", "phone")
    op.drop_column("profiles", "avatar_url")
    op.drop_column("profiles", "bio")
    op.drop_column("profiles", "headline")
    op.drop_column("profiles", "study_year")
    op.drop_column("profiles", "specialization")
    op.drop_column("profiles", "faculty")
    op.drop_index(op.f("ix_message_attachments_message_id"), table_name="message_attachments")
    op.drop_table("message_attachments")
    op.drop_index(
        "ix_messages_unread",
        table_name="messages",
        postgresql_where="status != 'read' AND is_deleted = false",
    )
    op.drop_index(op.f("ix_messages_status"), table_name="messages")
    op.drop_index(op.f("ix_messages_sender_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_message_type"), table_name="messages")
    op.drop_index(op.f("ix_messages_is_deleted"), table_name="messages")
    op.drop_index(op.f("ix_messages_created_at"), table_name="messages")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_index("ix_messages_conversation_created", table_name="messages")
    op.drop_table("messages")
    op.drop_index(
        op.f("ix_conversation_participants_created_at"), table_name="conversation_participants"
    )
    op.drop_index("ix_conv_participants_user", table_name="conversation_participants")
    op.drop_index("ix_conv_participants_unread", table_name="conversation_participants")
    op.drop_table("conversation_participants")
    op.drop_index(op.f("ix_recommendations_sender_id"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_recipient_id"), table_name="recommendations")
    op.drop_index("ix_recommendations_recipient", table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_opportunity_id"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_is_read"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_created_at"), table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_index(op.f("ix_opportunity_tags_created_at"), table_name="opportunity_tags")
    op.drop_index("ix_opp_tags_tag", table_name="opportunity_tags")
    op.drop_index("ix_opp_tags_opportunity", table_name="opportunity_tags")
    op.drop_table("opportunity_tags")
    op.drop_index(op.f("ix_opportunity_skills_created_at"), table_name="opportunity_skills")
    op.drop_index("ix_opp_skills_skill", table_name="opportunity_skills")
    op.drop_index("ix_opp_skills_opportunity", table_name="opportunity_skills")
    op.drop_table("opportunity_skills")
    op.drop_index(op.f("ix_favorites_user_id"), table_name="favorites")
    op.drop_index("ix_favorites_user", table_name="favorites")
    op.drop_index(op.f("ix_favorites_opportunity_id"), table_name="favorites")
    op.drop_index(op.f("ix_favorites_created_at"), table_name="favorites")
    op.drop_table("favorites")
    op.drop_index(op.f("ix_event_registrations_status"), table_name="event_registrations")
    op.drop_index(op.f("ix_event_registrations_profile_id"), table_name="event_registrations")
    op.drop_index(op.f("ix_event_registrations_opportunity_id"), table_name="event_registrations")
    op.drop_index(op.f("ix_event_registrations_created_at"), table_name="event_registrations")
    op.drop_index(op.f("ix_event_registrations_check_in_code"), table_name="event_registrations")
    op.drop_index("ix_event_reg_opportunity", table_name="event_registrations")
    op.drop_table("event_registrations")
    op.drop_index(op.f("ix_conversations_opportunity_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_last_message_at"), table_name="conversations")
    op.drop_index("ix_conversations_last_message", table_name="conversations")
    op.drop_index(op.f("ix_conversations_created_at"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index("ix_applications_status", table_name="applications")
    op.drop_index("ix_applications_opportunity_status", table_name="applications")
    op.drop_index(op.f("ix_applications_opportunity_id"), table_name="applications")
    op.drop_index(op.f("ix_applications_is_shortlisted"), table_name="applications")
    op.drop_index(op.f("ix_applications_created_at"), table_name="applications")
    op.drop_index("ix_applications_applicant_status", table_name="applications")
    op.drop_index(op.f("ix_applications_applicant_id"), table_name="applications")
    op.drop_table("applications")
    op.drop_index("ix_profile_skills_skill", table_name="profile_skills")
    op.drop_index("ix_profile_skills_profile", table_name="profile_skills")
    op.drop_index(op.f("ix_profile_skills_created_at"), table_name="profile_skills")
    op.drop_table("profile_skills")
    op.drop_index(op.f("ix_opportunities_work_format"), table_name="opportunities")
    op.drop_index("ix_opportunities_type_status", table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_type"), table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_title"), table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_status"), table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_salary_min"), table_name="opportunities")
    op.drop_index("ix_opportunities_salary", table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_published_at"), table_name="opportunities")
    op.drop_index("ix_opportunities_published", table_name="opportunities")
    op.drop_index("ix_opportunities_location", table_name="opportunities", postgresql_using="gist")
    op.drop_index(op.f("ix_opportunities_is_moderated"), table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_expires_at"), table_name="opportunities")
    op.drop_index("ix_opportunities_expires", table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_experience_level"), table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_event_start_at"), table_name="opportunities")
    op.drop_index("ix_opportunities_event_start", table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_employment_type"), table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_created_at"), table_name="opportunities")
    op.drop_index("ix_opportunities_company_status", table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_company_id"), table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_city"), table_name="opportunities")
    op.drop_index(
        "ix_opportunities_active", table_name="opportunities", postgresql_where="status = 'active'"
    )
    op.drop_table("opportunities")
    op.drop_index(op.f("ix_favorite_companies_user_id"), table_name="favorite_companies")
    op.drop_index(op.f("ix_favorite_companies_created_at"), table_name="favorite_companies")
    op.drop_index(op.f("ix_favorite_companies_company_id"), table_name="favorite_companies")
    op.drop_table("favorite_companies")
    op.drop_index("ix_company_verifications_status", table_name="company_verifications")
    op.drop_index(op.f("ix_company_verifications_created_at"), table_name="company_verifications")
    op.drop_index("ix_company_verifications_company", table_name="company_verifications")
    op.drop_table("company_verifications")
    op.drop_index(op.f("ix_tags_slug"), table_name="tags")
    op.drop_index(op.f("ix_tags_name"), table_name="tags")
    op.drop_index(op.f("ix_tags_is_approved"), table_name="tags")
    op.drop_index(op.f("ix_tags_created_at"), table_name="tags")
    op.drop_index(op.f("ix_tags_category"), table_name="tags")
    op.drop_table("tags")
    op.drop_index("ix_skills_usage", table_name="skills")
    op.drop_index(op.f("ix_skills_slug"), table_name="skills")
    op.drop_index(op.f("ix_skills_name"), table_name="skills")
    op.drop_index(op.f("ix_skills_is_approved"), table_name="skills")
    op.drop_index(op.f("ix_skills_created_at"), table_name="skills")
    op.drop_index("ix_skills_category_approved", table_name="skills")
    op.drop_index(op.f("ix_skills_category"), table_name="skills")
    op.drop_table("skills")
    op.drop_index(op.f("ix_reviews_target_type"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_target_id"), table_name="reviews")
    op.drop_index("ix_reviews_target", table_name="reviews")
    op.drop_index(op.f("ix_reviews_is_published"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_created_at"), table_name="reviews")
    op.drop_index("ix_reviews_author_target", table_name="reviews")
    op.drop_index(op.f("ix_reviews_author_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(op.f("ix_notifications_type"), table_name="notifications")
    op.drop_index("ix_notifications_recipient_unread", table_name="notifications")
    op.drop_index(op.f("ix_notifications_recipient_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_is_read"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_contacts_status"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_requester_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_created_at"), table_name="contacts")
    op.drop_index("ix_contacts_addressee_status", table_name="contacts")
    op.drop_index(op.f("ix_contacts_addressee_id"), table_name="contacts")
    op.drop_table("contacts")
    op.drop_index(op.f("ix_companies_verification_status"), table_name="companies")
    op.drop_index("ix_companies_verification", table_name="companies")
    op.drop_index(op.f("ix_companies_name"), table_name="companies")
    op.drop_index("ix_companies_location", table_name="companies", postgresql_using="gist")
    op.drop_index(op.f("ix_companies_is_active"), table_name="companies")
    op.drop_index(op.f("ix_companies_inn"), table_name="companies")
    op.drop_index(op.f("ix_companies_industry"), table_name="companies")
    op.drop_index(op.f("ix_companies_created_at"), table_name="companies")
    op.drop_index("ix_companies_city_active", table_name="companies")
    op.drop_index(op.f("ix_companies_city"), table_name="companies")
    op.drop_table("companies")
    # ### end Alembic commands ###
